# -- Main Menu --
[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "成语故事"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 30

# -- Footer Menu --
[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10
